### PR TITLE
Change Guide 

### PR DESCRIPTION
**Pull request by Notupus**
Change guide to network only as it works as well and fixed a few issues, shorter by 30 lines

### CODE REVIEW

**Comment by eimparas** [comment]
From my experiance dealing with these embeded devices  , its mutch safer to perfom the mod using the hardware serial console than ssh/scp. ( i had cases where the ssh console or the scp transfer would "crap out" and result in a bricked device )  But i see your point wanting to perform it using SSH . Its almost hasle free no device teardown no usb-ttl adapters . 

I would apriciate it if you re-write your PR to include both methods , ill be more than happy to merge it then !

**Comment by aka-khalid** [comment]
Hi @Notupus!
I have a VMG3625-T50B with blocked access to SSH so I used this [command-injection script](https://github.com/ThomasRinsma/vmg8825scripts/blob/main/cmd_injection_ping2.py) to gain root shell access on the router, but I'm having hard time following your method since I don't know how to use `scp` in my case. 

Also I couldn't find my device's `Model ID` in the provided Excel sheet so I don't know what to do about that either.

I would appreciate if you guide me through the correct way to debrand my device because I've been struggling for a couple days now and I don't have the knowledge to figure it out on my own.

Thanks.

**Comment by Notupus** [comment]
Hey, That sounds cool, this is a pull request I opened, I think it will be useful to document how this goes. If you can create an issue on this repo ( I am sure @eimparas wont mind), describing your device( isp etc etc how you got ssh ) so we can document it too for the next person who tries to do this. I will try and help you there.

**Comment by aka-khalid** [comment]
Created an [issue](https://github.com/eimparas/Zyxel-VMG8623-T50B-Debrand/issues/3#issue-2220605345). I don't know if I should add more info. Please take a look.

**Comment by eimparas** [comment]
> Hey, That sounds cool, this is a pull request I opened, I think it will be useful to document how this goes. If you can create an issue on this repo ( I am sure @eimparas wont mind), describing your device( isp etc etc how you got ssh ) so we can document it too for the next person who tries to do this. I will try and help you there.

I absolutly wont mind , if the dive into the VMG3625-T50B is done on a seperate Issue ! Our ISPs do not use this model here , so it would be realy intresting to see it capabilites! 

 as i see @aka-khalid has already opened a issue  (#3)  we can work from there . 


Also , @Notupus , any progress-updates on re write of the guide you PRed here ? IMHO its mutch better to include both methods

**Comment by eimparas** [comment]
Decided to merge the PR as is . After discussion i had with a colleague of mine , who we "Play arround" / tweek with CPEs together, 
he found your guide mutch easyer to follow than my write up . i will merge the PR

**Pull request merged**
